version: '3.2'
services:
  web:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    stdin_open: true
    environment:
      - NODE_ENV=dev
    command:
      sh -c '
      if test -d node_modules;
      then
      echo node_modules_exists;
      else
      cp -a /build/node_modules /app;
      fi &&
      yarn install && npm start'
